# ASRS Column Names inferred from 2024 data
COLUMN_NAMES = [
    "ACN", "Date", "Local Time Of Day", "Locale Reference", "State Reference", 
    "Relative Position.Angle.Radial", "Relative Position.Distance.Nautical Miles", 
    "Altitude.AGL.Single Value", "Altitude.MSL.Single Value", "Latitude / Longitude (UAS)", 
    "Flight Conditions", "Weather Elements / Visibility", "Work Environment Factor", 
    "Light", "Ceiling", "RVR.Single Value", "ATC / Advisory", "Aircraft Operator", 
    "Make Model Name", "Aircraft Zone", "Crew Size", "Operating Under FAR Part", 
    "Flight Plan", "Mission", "Nav In Use", "Flight Phase", "Route In Use", "Airspace", 
    "Maintenance Status.Maintenance Deferred", "Maintenance Status.Records Complete", 
    "Maintenance Status.Released For Service", "Maintenance Status.Required / Correct Doc On Board", 
    "Maintenance Status.Maintenance Type", "Maintenance Status.Maintenance Items Involved", 
    "Cabin Lighting", "Number Of Seats.Number", "Passengers On Board.Number", 
    "Crew Size Flight Attendant.Number Of Crew", "Airspace Authorization Provider (UAS)", 
    "Operating Under Waivers / Exemptions / Authorizations (UAS)", "Waivers / Exemptions / Authorizations (UAS)", 
    "Airworthiness Certification (UAS)", "Weight Category (UAS)", "Configuration (UAS)", 
    "Flight Operated As (UAS)", "Flight Operated with Visual Observer (UAS)", 
    "Control Mode (UAS)", "Flying In / Near / Over (UAS)", "Passenger Capable (UAS)", 
    "Type (UAS)", "Number of UAS Being Controlled (UAS)", "Aircraft Component", 
    "Manufacturer", "Aircraft Reference", "Problem", "ATC / Advisory.1", 
    "Aircraft Operator.1", "Make Model Name.1", "Aircraft Zone.1", "Crew Size.1", 
    "Operating Under FAR Part.1", "Flight Plan.1", "Mission.1", "Nav In Use.1", 
    "Flight Phase.1", "Route In Use.1", "Airspace.1", "Maintenance Status.Maintenance Deferred.1", 
    "Maintenance Status.Records Complete.1", "Maintenance Status.Released For Service.1", 
    "Maintenance Status.Required / Correct Doc On Board.1", "Maintenance Status.Maintenance Type.1", 
    "Maintenance Status.Maintenance Items Involved.1", "Cabin Lighting.1", "Number Of Seats.Number.1", 
    "Passengers On Board.Number.1", "Crew Size Flight Attendant.Number Of Crew.1", 
    "Airspace Authorization Provider (UAS).1", "Operating Under Waivers / Exemptions / Authorizations (UAS).1", 
    "Waivers / Exemptions / Authorizations (UAS).1", "Airworthiness Certification (UAS).1", 
    "Weight Category (UAS).1", "Configuration (UAS).1", "Flight Operated As (UAS).1", 
    "Flight Operated with Visual Observer (UAS).1", "Control Mode (UAS).1", 
    "Flying In / Near / Over (UAS).1", "Passenger Capable (UAS).1", "Type (UAS).1", 
    "Number of UAS Being Controlled (UAS).1", "Location Of Person", "Location In Aircraft", 
    "Reporter Organization", "Function", "Qualification", "Experience", "Cabin Activity", 
    "Human Factors", "Communication Breakdown", "UAS Communication Breakdown", 
    "ASRS Report Number.Accession Number", "Location Of Person.1", "Location In Aircraft.1", 
    "Reporter Organization.1", "Function.1", "Qualification.1", "Experience.1", 
    "Cabin Activity.1", "Human Factors.1", "Communication Breakdown.1", 
    "UAS Communication Breakdown.1", "ASRS Report Number.Accession Number.1", 
    "Anomaly", "Miss Distance", "Were Passengers Involved In Event", "Detector", 
    "When Detected", "Result", "Contributing Factors / Situations", "Primary Problem", 
    "Narrative", "Callback", "Narrative.1", "Callback.1", "Synopsis", "Unnamed: 125"
]
